---
- name: Get clusters list
  ansible.builtin.uri:
    url: "{{ nutanix_api_v3 }}/clusters/list"
    body:
      kind: cluster
      sort_order: ASCENDING
      offset: 0
      length: 10
      sort_attribute: ''
    method: POST
    validate_certs: 'no'
    body_format: json
    status_code: 200
    headers:
      Cookie: "{{ session_cookie }}"
  register: json_clusters_result
  ignore_errors: true

- name: Stash the Cluster UUIDs
  ansible.builtin.set_fact:
    cluster_uuids: "{{ json_clusters_result | json_query('json.entities[*].{name: spec.name, uuid: metadata.uuid}') }}"

- name: Debug | Print cluster name/UUIDs
  ansible.builtin.debug:
    var: cluster_uuids
  when: debug_exec
