---
- name: Get VMS list
  ansible.builtin.uri:
    url: "{{ nutanix_api_v3 }}/vms/list"
    body:
      kind: vm
      sort_order: ASCENDING
      offset: 0
      length: 1000
      sort_attribute: ''
    method: POST
    validate_certs: 'no'
    body_format: json
    status_code: 200
    headers:
      Cookie: "{{ session_cookie }}"
  register: vms_result
  ignore_errors: true

- name: Debug | Print VMs List
  ansible.builtin.debug:
    var: vms_result
  when: debug_exec

- name: Stash the VM UUIDs
  ansible.builtin.set_fact:
    vms_uuids: "{{ vms_uuids|default([]) + [{'name': item.spec.name, 'uuid': item.metadata.uuid}] }}"
  with_items: "{{ vms_result.json.entities }}"

- name: Debug | Print VMs UUIDs
  ansible.builtin.debug:
    var: vms_uuids
  when: debug_exec

- name: Add the list of vms to hosts
  ansible.builtin.add_host:
    name: "{{ item.name }}"
    groups: openshift
    uuid: "{{ item.uuid }}"
  with_items: "{{ vms_uuids }}"

- name: Debug | Print hostvars
  ansible.builtin.debug:
    var: hostvars
  when: debug_exec
