---
- name: Check if host already exist
  ansible.builtin.command: ping -c1 -w2 {{ item.ip }}
  with_items: "{{ vm_configuration }}"
  delegate_to: localhost
  register: ping_result
  ignore_errors: true
  changed_when: false

- name: Debug | Print ping command
  ansible.builtin.debug:
    msg: "{{ ping_result }}"
  when: debug_exec

- name: Set global facts from vm configuration
  ansible.builtin.set_fact:
    cluster_name: "NTNX-{{ item.cluster | upper }}-01"
    subnet_name: "{{ item.subnet }}"
  with_items:
    - "{{ vm_configuration }}"

- name: Debug | Print facts
  ansible.builtin.debug:
    msg:
      - 'subnet_name: {{ subnet_name }}'
      - 'cluster_name: {{ cluster_name }}'
  when: debug_exec

- name: Set facts - disk size
  ansible.builtin.set_fact:
    vm_cfg_disk: '{{ item.disk_size_GB * 1024 * 1024 * 1024 | int | default(omit) }}'
  with_items:
    - "{{ vm_configuration }}"
  when: item.disk_size_GB is defined

- name: Debug | Print disk size in bytes
  ansible.builtin.debug:
    var: vm_cfg_disk
  when:
    - vm_cfg_disk is defined
    - debug_exec

- name: When vm doesnt exist we create it
  when: ping_result is failed
  block:
    - name: Get session cookie
      ansible.builtin.import_tasks: get_session_cookie.yml

    - name: Get cluster uuids
      ansible.builtin.import_tasks: get_cluster_uuids.yml

    - name: Get subnet uuids
      ansible.builtin.import_tasks: get_subnet_uuids.yml

    - name: Get image uuids
      ansible.builtin.import_tasks: get_image_uuids.yml

    - name: Define uuids from names
      ansible.builtin.import_tasks: define_uuids_from_names.yml

    - name: Provisionning vm
      ansible.builtin.import_tasks: provision_vm.yml

    - name: Pause for 20 seconds to build vm
      ansible.builtin.pause:
        seconds: 20
        echo: "no"
      when: vm_cfg_disk is defined

    - name: Attach disk
      ansible.builtin.import_tasks: vm_attach_disk.yml
      when: vm_cfg_disk is defined

- name: When vm exist we configure it
  when: ping_result is succeeded
  block:
    - name: Get session cookie
      ansible.builtin.import_tasks: get_session_cookie.yml

    - name: Get vm details
      ansible.builtin.import_tasks: get_vm_details.yml

    - name: Resize vm ressources
      ansible.builtin.import_tasks: vm_details_resize.yml
      when: (vm_memory != vm_cfg_memory) or (vm_sockets != vm_cfg_sockets) or (vm_cores != vm_cfg_cores)

    - name: Attach Disk
      ansible.builtin.mport_tasks: vm_attach_disk.yml
      when:
        - vm_cfg_disk is defined
        - vm_disk == ""
